# Part 0: Import 套件

In [1]:
# 下載台股套件
import twstock

# 下載資料套件
import requests as r

# 資料處理套件
import pandas as pd

如果沒有上述套件 可以用pip install 或 conda install 指令安裝
- pip install twstock

# Part 1: 使用twstock套件 下載股市即時資料
- 使用說明：[twstock套件 - realtime](https://twstock.readthedocs.io/zh_TW/latest/quickstart.html#realtime)
- 資料來源：[基本市況報導網站](https://mis.twse.com.tw/stock/fibest.jsp)

### 台股歷史資料下載 Youtube影片
#### 1. 台股歷史資料下載：[【Python 爬蟲】台股個股資料免費下載｜選擇想要的個股資料！](https://youtu.be/_4CEymrQbV8)
#### 2. 一次下載多檔台股歷史資料：[【Python 爬蟲】台股個股資料免費下載｜個股資料 我全都要](https://youtu.be/wM5wJNgpIbA)

## Part 1.1: 下載一檔個股即時報價

In [2]:
stock = twstock.realtime.get('2330')
stock

{'timestamp': 1631843159.0,
 'info': {'code': '2330',
  'channel': '2330.tw',
  'name': '台積電',
  'fullname': '台灣積體電路製造股份有限公司',
  'time': '2021-09-17 09:45:59'},
 'realtime': {'latest_trade_price': '-',
  'trade_volume': '-',
  'accumulate_trade_volume': '4993',
  'best_bid_price': ['599.0000',
   '598.0000',
   '597.0000',
   '596.0000',
   '595.0000'],
  'best_bid_volume': ['396', '558', '429', '270', '684'],
  'best_ask_price': ['600.0000',
   '601.0000',
   '602.0000',
   '603.0000',
   '604.0000'],
  'best_ask_volume': ['816', '245', '395', '132', '101'],
  'open': '600.0000',
  'high': '602.0000',
  'low': '599.0000'},
 'success': True}

### 確認是否為即時資料

In [3]:
stock['success'] == True

True

In [4]:
"台股即時報價" if stock['success'] == True else "不是台股即時報價"

'台股即時報價'

### 資料整理

In [5]:
stock = pd.DataFrame(stock)
stock

,timestamp,info,realtime,success
code,1.631843e+09,2330,NaN,True
channel,1.631843e+09,2330.tw,NaN,True
name,1.631843e+09,台積電,NaN,True
fullname,1.631843e+09,台灣積體電路製造股份有限公司,NaN,True
time,1.631843e+09,2021-09-17 09:45:59,NaN,True
latest_trade_price,1.631843e+09,NaN,-,True
trade_volume,1.631843e+09,NaN,-,True
accumulate_trade_volume,1.631843e+09,NaN,4993,True
best_bid_price,1.631843e+09,NaN,"[599.0000, 598.0000, 597.0000, 596.0000, 595.0...",True
best_bid_volume,1.631843e+09,NaN,"[396, 558, 429, 270, 684]",True
best_ask_price,1.631843e+09,NaN,"[600.0000, 601.0000, 602.0000, 603.0000, 604.0...",True
best_ask_volume,1.631843e+09,NaN,"[816, 245, 395, 132, 101]",True
open,1.631843e+09,NaN,600.0000,True
high,1.631843e+09,NaN,602.0000,True
low,1.631843e+09,NaN,599.0000,True

In [6]:
stock_info = stock.iloc[0:5, 1]
stock_info

code                       2330
channel                 2330.tw
name                        台積電
fullname         台灣積體電路製造股份有限公司
time        2021-09-17 09:45:59
Name: info, dtype: object

In [7]:
stock_realtime = stock.iloc[5:, 2]
stock_realtime

latest_trade_price                                                         -
trade_volume                                                               -
accumulate_trade_volume                                                 4993
best_bid_price             [599.0000, 598.0000, 597.0000, 596.0000, 595.0...
best_bid_volume                                    [396, 558, 429, 270, 684]
best_ask_price             [600.0000, 601.0000, 602.0000, 603.0000, 604.0...
best_ask_volume                                    [816, 245, 395, 132, 101]
open                                                                600.0000
high                                                                602.0000
low                                                                 599.0000
Name: realtime, dtype: object

In [8]:
stock_data = stock_info.append(stock_realtime, ignore_index = True)
stock_data

0                                                  2330
1                                               2330.tw
2                                                   台積電
3                                        台灣積體電路製造股份有限公司
4                                   2021-09-17 09:45:59
5                                                     -
6                                                     -
7                                                  4993
8     [599.0000, 598.0000, 597.0000, 596.0000, 595.0...
9                             [396, 558, 429, 270, 684]
10    [600.0000, 601.0000, 602.0000, 603.0000, 604.0...
11                            [816, 245, 395, 132, 101]
12                                             600.0000
13                                             602.0000
14                                             599.0000
dtype: object

In [9]:
stock['data'] = list(stock_data)
stock

,timestamp,info,realtime,success,data
code,1.631843e+09,2330,NaN,True,2330
channel,1.631843e+09,2330.tw,NaN,True,2330.tw
name,1.631843e+09,台積電,NaN,True,台積電
fullname,1.631843e+09,台灣積體電路製造股份有限公司,NaN,True,台灣積體電路製造股份有限公司
time,1.631843e+09,2021-09-17 09:45:59,NaN,True,2021-09-17 09:45:59
latest_trade_price,1.631843e+09,NaN,-,True,-
trade_volume,1.631843e+09,NaN,-,True,-
accumulate_trade_volume,1.631843e+09,NaN,4993,True,4993
best_bid_price,1.631843e+09,NaN,"[599.0000, 598.0000, 597.0000, 596.0000, 595.0...",True,"[599.0000, 598.0000, 597.0000, 596.0000, 595.0..."
best_bid_volume,1.631843e+09,NaN,"[396, 558, 429, 270, 684]",True,"[396, 558, 429, 270, 684]"
best_ask_price,1.631843e+09,NaN,"[600.0000, 601.0000, 602.0000, 603.0000, 604.0...",True,"[600.0000, 601.0000, 602.0000, 603.0000, 604.0..."
best_ask_volume,1.631843e+09,NaN,"[816, 245, 395, 132, 101]",True,"[816, 245, 395, 132, 101]"
open,1.631843e+09,NaN,600.0000,True,600.0000
high,1.631843e+09,NaN,602.0000,True,602.0000
low,1.631843e+09,NaN,599.0000,True,599.0000

In [10]:
stock = stock.drop(['timestamp', 'info', 'realtime', 'success'], axis = 1)
stock

                                                                      data
code                                                                  2330
channel                                                            2330.tw
name                                                                   台積電
fullname                                                    台灣積體電路製造股份有限公司
time                                                   2021-09-17 09:45:59
latest_trade_price                                                       -
trade_volume                                                             -
accumulate_trade_volume                                               4993
best_bid_price           [599.0000, 598.0000, 597.0000, 596.0000, 595.0...
best_bid_volume                                  [396, 558, 429, 270, 684]
best_ask_price           [600.0000, 601.0000, 602.0000, 603.0000, 604.0...
best_ask_volume                                  [816, 245, 395, 132, 101]
open                                                              600.0000
high                                                              602.0000
low                                                               599.0000

In [11]:
stock = stock.T
stock

,code,channel,name,fullname,time,latest_trade_price,trade_volume,accumulate_trade_volume,best_bid_price,best_bid_volume,best_ask_price,best_ask_volume,open,high,low
data,2330,2330.tw,台積電,台灣積體電路製造股份有限公司,2021-09-17 09:45:59,-,-,4993,"[599.0000, 598.0000, 597.0000, 596.0000, 595.0...","[396, 558, 429, 270, 684]","[600.0000, 601.0000, 602.0000, 603.0000, 604.0...","[816, 245, 395, 132, 101]",600.0000,602.0000,599.0000

In [12]:
stock.columns = ['股票代碼', '股票代碼全', '股票名稱', '公司名','下載時間', '最新成交價', '成交量', '累計成交量', '最佳5檔賣出價', '最佳5檔賣出量', '最佳5檔買進價', '最佳5檔買進量', '開盤價', '最高價', '最低價']
stock

,股票代碼,股票代碼全,股票名稱,公司名,下載時間,最新成交價,成交量,累計成交量,最佳5檔賣出價,最佳5檔賣出量,最佳5檔買進價,最佳5檔買進量,開盤價,最高價,最低價
data,2330,2330.tw,台積電,台灣積體電路製造股份有限公司,2021-09-17 09:45:59,-,-,4993,"[599.0000, 598.0000, 597.0000, 596.0000, 595.0...","[396, 558, 429, 270, 684]","[600.0000, 601.0000, 602.0000, 603.0000, 604.0...","[816, 245, 395, 132, 101]",600.0000,602.0000,599.0000

## Part 1.2: 下載多檔個股即時報價

In [13]:
stock_multi = twstock.realtime.get(['2330', '2454', '0050'])
stock_multi

{'2330': {'timestamp': 1631843380.0,
  'info': {'code': '2330',
   'channel': '2330.tw',
   'name': '台積電',
   'fullname': '台灣積體電路製造股份有限公司',
   'time': '2021-09-17 09:49:40'},
  'realtime': {'latest_trade_price': '601.0000',
   'trade_volume': '17',
   'accumulate_trade_volume': '5947',
   'best_bid_price': ['600.0000',
    '599.0000',
    '598.0000',
    '597.0000',
    '596.0000'],
   'best_bid_volume': ['386', '287', '556', '433', '272'],
   'best_ask_price': ['601.0000',
    '602.0000',
    '603.0000',
    '604.0000',
    '605.0000'],
   'best_ask_volume': ['161', '380', '153', '100', '192'],
   'open': '600.0000',
   'high': '602.0000',
   'low': '599.0000'},
  'success': True},
 '2454': {'timestamp': 1631843381.0,
  'info': {'code': '2454',
   'channel': '2454.tw',
   'name': '聯發科',
   'fullname': '聯發科技股份有限公司',
   'time': '2021-09-17 09:49:41'},
  'realtime': {'latest_trade_price': '946.0000',
   'trade_volume': '1',
   'accumulate_trade_volume': '1591',
   'best_bid_price': ['945.0000',
    '944.0000',
    '943.0000',
    '942.0000',
    '941.0000'],
   'best_bid_volume': ['55', '17', '12', '15', '21'],
   'best_ask_price': ['946.0000',
    '947.0000',
    '948.0000',
    '949.0000',
    '950.0000'],
   'best_ask_volume': ['44', '32', '82', '118', '253'],
   'open': '940.0000',
   'high': '948.0000',
   'low': '936.0000'},
  'success': True},
 '0050': {'timestamp': 1631843377.0,
  'info': {'code': '0050',
   'channel': '0050.tw',
   'name': '元大台灣50',
   'fullname': '元大台灣卓越50證券投資信託基金',
   'time': '2021-09-17 09:49:37'},
  'realtime': {'latest_trade_price': '-',
   'trade_volume': '-',
   'accumulate_trade_volume': '1019',
   'best_bid_price': ['139.9000',
    '139.8500',
    '139.8000',
    '139.7500',
    '139.7000'],
   'best_bid_volume': ['100', '191', '134', '38', '29'],
   'best_ask_price': ['139.9500',
    '140.0500',
    '140.1000',
    '140.1500',
    '140.2000'],
   'best_ask_volume': ['2', '24', '51', '3', '3'],
   'open': '140.1000',
   'high': '140.1000',
   'low': '139.5000'},
  'success': True},
 'success': True}

In [14]:
pd.DataFrame(stock_multi)

,2330,2454,0050,success
timestamp,1631843380.0,1631843381.0,1631843377.0,True
info,"{'code': '2330', 'channel': '2330.tw', 'name':...","{'code': '2454', 'channel': '2454.tw', 'name':...","{'code': '0050', 'channel': '0050.tw', 'name':...",True
realtime,"{'latest_trade_price': '601.0000', 'trade_volu...","{'latest_trade_price': '946.0000', 'trade_volu...","{'latest_trade_price': '-', 'trade_volume': '-...",True
success,True,True,True,True

### 拆分成單一個股

In [15]:
df = stock_multi['2330']
df

{'timestamp': 1631843380.0,
 'info': {'code': '2330',
  'channel': '2330.tw',
  'name': '台積電',
  'fullname': '台灣積體電路製造股份有限公司',
  'time': '2021-09-17 09:49:40'},
 'realtime': {'latest_trade_price': '601.0000',
  'trade_volume': '17',
  'accumulate_trade_volume': '5947',
  'best_bid_price': ['600.0000',
   '599.0000',
   '598.0000',
   '597.0000',
   '596.0000'],
  'best_bid_volume': ['386', '287', '556', '433', '272'],
  'best_ask_price': ['601.0000',
   '602.0000',
   '603.0000',
   '604.0000',
   '605.0000'],
  'best_ask_volume': ['161', '380', '153', '100', '192'],
  'open': '600.0000',
  'high': '602.0000',
  'low': '599.0000'},
 'success': True}

#### 確認是否為即時資料

In [16]:
df['success']

True

In [17]:
df = pd.DataFrame(df)
df

,timestamp,info,realtime,success
code,1.631843e+09,2330,NaN,True
channel,1.631843e+09,2330.tw,NaN,True
name,1.631843e+09,台積電,NaN,True
fullname,1.631843e+09,台灣積體電路製造股份有限公司,NaN,True
time,1.631843e+09,2021-09-17 09:49:40,NaN,True
latest_trade_price,1.631843e+09,NaN,601.0000,True
trade_volume,1.631843e+09,NaN,17,True
accumulate_trade_volume,1.631843e+09,NaN,5947,True
best_bid_price,1.631843e+09,NaN,"[600.0000, 599.0000, 598.0000, 597.0000, 596.0...",True
best_bid_volume,1.631843e+09,NaN,"[386, 287, 556, 433, 272]",True
best_ask_price,1.631843e+09,NaN,"[601.0000, 602.0000, 603.0000, 604.0000, 605.0...",True
best_ask_volume,1.631843e+09,NaN,"[161, 380, 153, 100, 192]",True
open,1.631843e+09,NaN,600.0000,True
high,1.631843e+09,NaN,602.0000,True
low,1.631843e+09,NaN,599.0000,True

In [18]:
stock_info = df.iloc[0:5, 1]
stock_realtime = df.iloc[5:, 2]
stock_data = stock_info.append(stock_realtime, ignore_index = True)
df['data'] = list(stock_data)
df = df.drop(['timestamp', 'info', 'realtime', 'success'], axis = 1)
df = df.T
df.columns = ['股票代碼', '股票代碼全', '股票名稱', '公司名','下載時間', '最新成交價', '成交量', '累計成交量', '最佳5檔賣出價', '最佳5檔賣出量', '最佳5檔買進價', '最佳5檔買進量', '開盤價', '最高價', '最低價']
df

,股票代碼,股票代碼全,股票名稱,公司名,下載時間,最新成交價,成交量,累計成交量,最佳5檔賣出價,最佳5檔賣出量,最佳5檔買進價,最佳5檔買進量,開盤價,最高價,最低價
data,2330,2330.tw,台積電,台灣積體電路製造股份有限公司,2021-09-17 09:49:40,601.0000,17,5947,"[600.0000, 599.0000, 598.0000, 597.0000, 596.0...","[386, 287, 556, 433, 272]","[601.0000, 602.0000, 603.0000, 604.0000, 605.0...","[161, 380, 153, 100, 192]",600.0000,602.0000,599.0000

In [19]:
stock_df = pd.DataFrame()

for stock in ['2330', '2454', '0050']:
    df_ = pd.DataFrame(stock_multi[stock])
    stock_info = df_.iloc[0:5, 1]
    stock_realtime = df_.iloc[5:, 2]
    stock_data = stock_info.append(stock_realtime, ignore_index = True)
    df_['data'] = list(stock_data)
    df_ = df_.drop(['timestamp', 'info', 'realtime', 'success'], axis = 1)
    df_ = df_.T
    stock_df = stock_df.append(df_, ignore_index = True)

In [20]:
stock_df

,code,channel,name,fullname,time,latest_trade_price,trade_volume,accumulate_trade_volume,best_bid_price,best_bid_volume,best_ask_price,best_ask_volume,open,high,low
0,2330,2330.tw,台積電,台灣積體電路製造股份有限公司,2021-09-17 09:49:40,601.0000,17,5947,"[600.0000, 599.0000, 598.0000, 597.0000, 596.0...","[386, 287, 556, 433, 272]","[601.0000, 602.0000, 603.0000, 604.0000, 605.0...","[161, 380, 153, 100, 192]",600.0000,602.0000,599.0000
1,2454,2454.tw,聯發科,聯發科技股份有限公司,2021-09-17 09:49:41,946.0000,1,1591,"[945.0000, 944.0000, 943.0000, 942.0000, 941.0...","[55, 17, 12, 15, 21]","[946.0000, 947.0000, 948.0000, 949.0000, 950.0...","[44, 32, 82, 118, 253]",940.0000,948.0000,936.0000
2,0050,0050.tw,元大台灣50,元大台灣卓越50證券投資信託基金,2021-09-17 09:49:37,-,-,1019,"[139.9000, 139.8500, 139.8000, 139.7500, 139.7...","[100, 191, 134, 38, 29]","[139.9500, 140.0500, 140.1000, 140.1500, 140.2...","[2, 24, 51, 3, 3]",140.1000,140.1000,139.5000

In [21]:
stock_df.columns = ['股票代碼', '股票代碼全', '股票名稱', '公司名','下載時間', '最新成交價', '成交量', '累計成交量', '最佳5檔賣出價', '最佳5檔賣出量', '最佳5檔買進價', '最佳5檔買進量', '開盤價', '最高價', '最低價']
stock_df

,股票代碼,股票代碼全,股票名稱,公司名,下載時間,最新成交價,成交量,累計成交量,最佳5檔賣出價,最佳5檔賣出量,最佳5檔買進價,最佳5檔買進量,開盤價,最高價,最低價
0,2330,2330.tw,台積電,台灣積體電路製造股份有限公司,2021-09-17 09:49:40,601.0000,17,5947,"[600.0000, 599.0000, 598.0000, 597.0000, 596.0...","[386, 287, 556, 433, 272]","[601.0000, 602.0000, 603.0000, 604.0000, 605.0...","[161, 380, 153, 100, 192]",600.0000,602.0000,599.0000
1,2454,2454.tw,聯發科,聯發科技股份有限公司,2021-09-17 09:49:41,946.0000,1,1591,"[945.0000, 944.0000, 943.0000, 942.0000, 941.0...","[55, 17, 12, 15, 21]","[946.0000, 947.0000, 948.0000, 949.0000, 950.0...","[44, 32, 82, 118, 253]",940.0000,948.0000,936.0000
2,0050,0050.tw,元大台灣50,元大台灣卓越50證券投資信託基金,2021-09-17 09:49:37,-,-,1019,"[139.9000, 139.8500, 139.8000, 139.7500, 139.7...","[100, 191, 134, 38, 29]","[139.9500, 140.0500, 140.1000, 140.1500, 140.2...","[2, 24, 51, 3, 3]",140.1000,140.1000,139.5000

## Part 1.3: 把下載的資料另存成csv檔

In [22]:
stock_df.to_csv('realtime.csv')

# Part 2: 怎麼下載 "盤中零股" 行情資料
資料來源：[基本市況報導網站](https://mis.twse.com.tw/stock/fibest.jsp)

## Part 2.1: 下載"上市公司 盤中零股"即時行情

In [23]:
url = "https://mis.twse.com.tw/stock/api/getOddInfo.jsp?ex_ch=tse_2330.tw"

In [24]:
res = r.get(url)
res

In [25]:
data = res.json()
data

{'msgArray': [{'tt': '09:52:05',
   'tv': '-',
   'ps': '2107',
   'pz': '601.0000',
   'qmt': '770921',
   'tmt': '193725',
   'a': '602.0000_603.0000_604.0000_605.0000_606.0000_',
   'b': '601.0000_600.0000_599.0000_598.0000_597.0000_',
   'c': '2330',
   'qt': '09:54:15',
   'd': '20210917',
   'ch': '2330.tw',
   'tlong': '1631843655000',
   'f': '7939_6721_4008_6358_3482_',
   'ip': '0',
   'g': '2703_70355_32863_34626_16628_',
   'mt': '770921',
   'h': '602.0000',
   'i': '24',
   'it': '12',
   'l': '600.0000',
   'n': '台積電',
   'o': '601.0000',
   'p': '0',
   'ex': 'tse',
   's': '3495',
   't': '09:54:15',
   'u': '660.0000',
   'v': '64197',
   'w': '540.0000',
   'nf': '台灣積體電路製造股份有限公司',
   'y': '600.0000',
   'z': '601.0000',
   'ts': '1'}],
 'referer': '',
 'userDelay': 5000,
 'rtcode': '0000',
 'queryTime': {'sysDate': '20210917',
  'oddInfo': 98664,
  'oddInfoItem': 6,
  'sessionStr': 'UserSession',
  'sysTime': '09:54:19',
  'showChart': False,
  'sessionFromTime': 1631843645735,
  'sessionLatestTime': 1631843645735},
 'rtmessage': 'OK',
 'exKey': 'if_tse_2330.tw_zh-tw.null',
 'cachedAlive': 1366}

In [26]:
data['msgArray'][0]

{'tt': '09:52:05',
 'tv': '-',
 'ps': '2107',
 'pz': '601.0000',
 'qmt': '770921',
 'tmt': '193725',
 'a': '602.0000_603.0000_604.0000_605.0000_606.0000_',
 'b': '601.0000_600.0000_599.0000_598.0000_597.0000_',
 'c': '2330',
 'qt': '09:54:15',
 'd': '20210917',
 'ch': '2330.tw',
 'tlong': '1631843655000',
 'f': '7939_6721_4008_6358_3482_',
 'ip': '0',
 'g': '2703_70355_32863_34626_16628_',
 'mt': '770921',
 'h': '602.0000',
 'i': '24',
 'it': '12',
 'l': '600.0000',
 'n': '台積電',
 'o': '601.0000',
 'p': '0',
 'ex': 'tse',
 's': '3495',
 't': '09:54:15',
 'u': '660.0000',
 'v': '64197',
 'w': '540.0000',
 'nf': '台灣積體電路製造股份有限公司',
 'y': '600.0000',
 'z': '601.0000',
 'ts': '1'}

## Part 2.2: 下載"上櫃公司 盤中零股"即時行情

In [27]:
url = "https://mis.twse.com.tw/stock/api/getOddInfo.jsp?ex_ch=otc_8436.tw"

In [28]:
res = r.get(url)
res

In [29]:
data = res.json()
data

{'msgArray': [{'tt': '09:55:09',
   'tv': '-',
   'ps': '-',
   'pz': '-',
   'qmt': '126619',
   'tmt': '069005',
   'a': '234.0000_235.0000_236.0000_237.0000_238.0000_',
   'b': '231.5000_231.0000_230.5000_230.0000_229.0000_',
   'c': '8436',
   'qt': '09:55:29',
   'd': '20210917',
   'ch': '8436.tw',
   'tlong': '1631843729000',
   'f': '30_143_100_677_50_',
   'ip': '0',
   'g': '160_517_345_1025_67_',
   'mt': '126619',
   'h': '235.0000',
   'i': '22',
   'it': '12',
   'l': '232.0000',
   'n': '大江',
   'o': '235.0000',
   'p': '50',
   'ex': 'otc',
   's': '-',
   't': '09:55:29',
   'u': '254.5000',
   'v': '2653',
   'w': '208.5000',
   'nf': '大江生醫股份有限公司',
   'y': '231.5000',
   'z': '232.0000',
   'ts': '1'}],
 'referer': '',
 'userDelay': 5000,
 'rtcode': '0000',
 'queryTime': {'sysDate': '20210917',
  'oddInfo': 36812,
  'oddInfoItem': 7,
  'sessionStr': 'UserSession',
  'sysTime': '09:55:42',
  'showChart': False,
  'sessionFromTime': -1,
  'sessionLatestTime': -1},
 'rtmessage': 'OK'}

In [30]:
data['msgArray'][0]

{'tt': '09:55:09',
 'tv': '-',
 'ps': '-',
 'pz': '-',
 'qmt': '126619',
 'tmt': '069005',
 'a': '234.0000_235.0000_236.0000_237.0000_238.0000_',
 'b': '231.5000_231.0000_230.5000_230.0000_229.0000_',
 'c': '8436',
 'qt': '09:55:29',
 'd': '20210917',
 'ch': '8436.tw',
 'tlong': '1631843729000',
 'f': '30_143_100_677_50_',
 'ip': '0',
 'g': '160_517_345_1025_67_',
 'mt': '126619',
 'h': '235.0000',
 'i': '22',
 'it': '12',
 'l': '232.0000',
 'n': '大江',
 'o': '235.0000',
 'p': '50',
 'ex': 'otc',
 's': '-',
 't': '09:55:29',
 'u': '254.5000',
 'v': '2653',
 'w': '208.5000',
 'nf': '大江生醫股份有限公司',
 'y': '231.5000',
 'z': '232.0000',
 'ts': '1'}

## Part 2.3: 下載"上市公司 整股"即時行情

In [31]:
url = "https://mis.twse.com.tw/stock/api/getStockInfo.jsp?ex_ch=tse_2330.tw"

In [32]:
res = r.get(url)
res

In [33]:
data = res.json()
data

{'msgArray': [{'tv': '-',
   'ps': '-',
   'pz': '-',
   'bp': '0',
   'a': '602.0000_603.0000_604.0000_605.0000_606.0000_',
   'b': '601.0000_600.0000_599.0000_598.0000_597.0000_',
   'c': '2330',
   'd': '20210917',
   'ch': '2330.tw',
   'tlong': '1631843765000',
   'f': '333_155_283_353_128_',
   'ip': '0',
   'g': '306_418_463_522_424_',
   'mt': '811713',
   'h': '602.0000',
   'i': '24',
   'it': '12',
   'l': '599.0000',
   'n': '台積電',
   'o': '600.0000',
   'p': '0',
   'ex': 'tse',
   's': '-',
   't': '09:56:05',
   'u': '660.0000',
   'v': '6183',
   'w': '540.0000',
   'nf': '台灣積體電路製造股份有限公司',
   'y': '600.0000',
   'z': '-',
   'ts': '0'}],
 'referer': '',
 'userDelay': 5000,
 'rtcode': '0000',
 'queryTime': {'sysDate': '20210917',
  'stockInfoItem': 1040,
  'stockInfo': 1583710,
  'sessionStr': 'UserSession',
  'sysTime': '09:56:11',
  'showChart': False,
  'sessionFromTime': -1,
  'sessionLatestTime': -1},
 'rtmessage': 'OK',
 'exKey': 'if_tse_2330.tw_zh-tw.null',
 'cachedAlive': 31747}

In [34]:
data['msgArray'][0]

{'tv': '-',
 'ps': '-',
 'pz': '-',
 'bp': '0',
 'a': '602.0000_603.0000_604.0000_605.0000_606.0000_',
 'b': '601.0000_600.0000_599.0000_598.0000_597.0000_',
 'c': '2330',
 'd': '20210917',
 'ch': '2330.tw',
 'tlong': '1631843765000',
 'f': '333_155_283_353_128_',
 'ip': '0',
 'g': '306_418_463_522_424_',
 'mt': '811713',
 'h': '602.0000',
 'i': '24',
 'it': '12',
 'l': '599.0000',
 'n': '台積電',
 'o': '600.0000',
 'p': '0',
 'ex': 'tse',
 's': '-',
 't': '09:56:05',
 'u': '660.0000',
 'v': '6183',
 'w': '540.0000',
 'nf': '台灣積體電路製造股份有限公司',
 'y': '600.0000',
 'z': '-',
 'ts': '0'}

## Part 2.4: 下載"上櫃公司 整股"即時行情

In [35]:
url = "https://mis.twse.com.tw/stock/api/getStockInfo.jsp?ex_ch=otc_8436.tw"

In [36]:
res = r.get(url)
res

In [37]:
data = res.json()
data

{'msgArray': [{'tv': '-',
   'ps': '-',
   'pz': '-',
   'bp': '0',
   'a': '231.5000_232.0000_232.5000_233.0000_233.5000_',
   'b': '230.5000_230.0000_229.5000_229.0000_228.5000_',
   'c': '8436',
   'd': '20210917',
   'ch': '8436.tw',
   'tlong': '1631843834000',
   'f': '6_11_9_18_12_',
   'ip': '0',
   'g': '9_25_13_21_13_',
   'mt': '735562',
   'h': '236.0000',
   'i': '22',
   'it': '12',
   'l': '230.0000',
   'n': '大江',
   'o': '231.5000',
   'p': '0',
   'ex': 'otc',
   's': '-',
   't': '09:57:14',
   'u': '254.5000',
   'v': '371',
   'w': '208.5000',
   'nf': '大江生醫股份有限公司',
   'y': '231.5000',
   'z': '-',
   'ts': '0'}],
 'referer': '',
 'userDelay': 5000,
 'rtcode': '0000',
 'queryTime': {'sysDate': '20210917',
  'stockInfoItem': 1851,
  'stockInfo': 3746552,
  'sessionStr': 'UserSession',
  'sysTime': '09:57:23',
  'showChart': False,
  'sessionFromTime': -1,
  'sessionLatestTime': -1},
 'rtmessage': 'OK'}

In [38]:
data['msgArray'][0]

{'tv': '-',
 'ps': '-',
 'pz': '-',
 'bp': '0',
 'a': '231.5000_232.0000_232.5000_233.0000_233.5000_',
 'b': '230.5000_230.0000_229.5000_229.0000_228.5000_',
 'c': '8436',
 'd': '20210917',
 'ch': '8436.tw',
 'tlong': '1631843834000',
 'f': '6_11_9_18_12_',
 'ip': '0',
 'g': '9_25_13_21_13_',
 'mt': '735562',
 'h': '236.0000',
 'i': '22',
 'it': '12',
 'l': '230.0000',
 'n': '大江',
 'o': '231.5000',
 'p': '0',
 'ex': 'otc',
 's': '-',
 't': '09:57:14',
 'u': '254.5000',
 'v': '371',
 'w': '208.5000',
 'nf': '大江生醫股份有限公司',
 'y': '231.5000',
 'z': '-',
 'ts': '0'}